Repository arturmekler/FitnessClub, pull requests merged in 2020-07, with the labels that each got.

#11 [FEATURE] Add CODEOWNERS file
  .github/CODEOWNERS
Labels: enhancement

#12 [FEATURE] Add PR Template
  .github/pull_request_template.md
Labels: enhancement

#10 [FEATURE] Add few components to nav-menu
  ClientApp/src/app/app.module.ts
  ClientApp/src/app/chat/chat.component.css
  ClientApp/src/app/chat/chat.component.html
  ClientApp/src/app/chat/chat.component.spec.ts
  ClientApp/src/app/chat/chat.component.ts
  ClientApp/src/app/nav-menu/nav-menu.component.html
  ClientApp/src/app/sign-up-for-classes/sign-up-for-classes.component.css
  ClientApp/src/app/sign-up-for-classes/sign-up-for-classes.component.html
  ClientApp/src/app/sign-up-for-classes/sign-up-for-classes.component.spec.ts
  ClientApp/src/app/sign-up-for-classes/sign-up-for-classes.component.ts
  ClientApp/src/app/user-profile/user-profile.component.css
  ClientApp/src/app/user-profile/user-profile.component.html
  ClientApp/src/app/user-profile/user-profile.component.spec.ts
  ClientApp/src/app/user-profile/user-profile.component.ts
  ClientApp/src/app/user-schedule/user-schedule.component.css
  ClientApp/src/app/user-schedule/user-schedule.component.html
  ClientApp/src/app/user-schedule/user-schedule.component.spec.ts
  ClientApp/src/app/user-schedule/user-schedule.component.ts
Labels: feature

#14 [CI] Add Pull Request title check
  .github/workflows/pr-title-check.yml
Labels: CI

#13 [DOCUMENTATION] Update README.md
  README.md
Labels: documentation

#15 [CI] Add HTML5 Check
  .github/workflows/html-check.yml
Labels: CI

#20 [CI] Remove HTML5 check
  .github/workflows/html-check.yml
Labels: CI
